runtime: java
env: flex
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "21"
env_variables:
  DATABASE_URL: jdbc:postgresql://aws-0-ap-southeast-2:pooler:supabase:com:5432/postgres
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1